run:
  skip-files:
    - graph/generated/generated.go
  skip-dirs:
    - e2e/
  issues-exit-code: 0
  tests: false

issues:
  exclude-rules:
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
linters-settings:
  gosec:
    config:
      G306: "0600"
      G101:
        pattern: "(?i)example"
        ignore_entropy: false
        entropy_threshold: "80.0"
        per_char_threshold: "3.0"
        truncate: "32"
  gci:
    local-prefixes: github.com/favonia/cloudflare-ddns-go
  maligned:
    suggest-new: true
  exhaustive:
    default-signifies-exhaustive: true

linters:
  enable-all: true
  disable: maligned,interfacer,nlreturn,wsl,scopelint,golint
