name: Deploy

on:
  push:
    branches:
      - main
env:
  REVIEW_APP_YAML: ${{ secrets.REVIEW_APP_YAML }}
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create .env file
      run: echo $REVIEW_APP_YAML | base64 --decode -i > ./app.yaml
    - name: Create serviceAccount.json file
      run: echo $SERVICE_ACCOUNT_JSON | base64 --decode -i > ./serviceAccount.json
    - name: Create memoir-review.json file
      run: echo $GCP_SERVICE_ACCOUNT_JSON | base64 --decode -i > ./memoir-review.json
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Use gcloud CLI
      run: gcloud app deploy --quiet app.yaml