name: Deploy Production

on:
  push:
    tags:
      - 'v*'
env:
  APP_YAML: ${{ secrets.PRODUCTION_APP_YAML }}
  SERVICE_ACCOUNT_JSON: ${{ secrets.PRODUCTION_SERVICE_ACCOUNT_JSON }}
  GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.PRODUCTION_GCP_SERVICE_ACCOUNT_JSON }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create .env file
      run: echo $APP_YAML | base64 --decode -i > ./app.yaml
    - name: Create serviceAccount.json file
      run: echo $SERVICE_ACCOUNT_JSON | base64 --decode -i > ./serviceAccount.json
    - name: Create gcpServiceAccount.json file
      run: echo $GCP_SERVICE_ACCOUNT_JSON | base64 --decode -i > ./gcpServiceAccount.json
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.PRODUCTION_GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.PRODUCTION_GCP_SERVICE_ACCOUNT_JSON }}
        export_default_credentials: true
    - name: set env
      run: echo "release_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Use gcloud CLI
      run: |
        echo -e "env_variables:\n  RELEASE_INSTANCE_VERSION: ${{ env.release_version }}" >> release.yaml
        cat release.yaml
        gcloud app deploy --quiet app.yaml --version=${{env.release_version//./-}}
